### ISSUE TITLE
Add option to build using AWS

### ISSUE THREAD

**Issue by mpapis** [rvm/rvm-binary#11]

**Comment by jrgifford** [comment]
So I'm guessing that the primary advantage of building using AWS is that it gets scripted and re-run every week?

**Comment by mpapis** [comment]
does not have to be ran every week, but can be ran remotely without involving heavy work on local machine - problem with it would be:

1. someone has to pay for it
2. we are limited to available images, and we can not actually tell if the image was not tweaked in a way that would break compatibility with manual installations of given system

**Comment by jrgifford** [comment]
So doing it locally is probably best for now

- James



On Fri, Feb 20, 2015, at 12:20 PM, Michal Papis wrote:
> does not have to be ran every week, but can be ran remotely without
> involving heavy work on local machine - problem with it would be:


>  1. someone has to pay for it
>  2. we are limited to available images, and we can not actually tell
>     if the image was not tweaked in a way that would break
>     compatibility with manual installations of given system — Reply to
>     this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/rvm/rvm-binary/issues/11#issuecomment-75279198

**Comment by mpapis** [comment]
indeed, closing, I will investigate remote building when RVM2 is done
