### ISSUE TITLE
Rebuild/update Ruby 2.2 and 

### ISSUE THREAD

**Issue by jrgifford** [rvm/rvm-binary#21]
- [x] Ruby 2.2 was released 
- [x] New Ubuntu 12.04 LTS point release
- [x] New Ubuntu 14.04 LTS point release
- [x] New Fedora images
- [ ] New OpenSUSE Images as well ( :question: )
- [x] debian images?

**Comment by mpapis** [comment]
point releases are not important, check https://rvm.io/binaries/ for which part of version matters
