### ISSUE TITLE
How to build binaries?

### ISSUE THREAD

**Issue by anothermh** [rvm/rvm-binary#27]
I want to build binaries for rvm so I can use them internally across multiple machines rather than building from source. The README does not provide an example for creating binaries. Can someone please explain how this suite is used to build binaries by providing some example commands?

For example, I want to be able to build Ruby 2.3.3 for Debian/Ubuntu from an OSX machine. Can this suite be used for that purpose?

**Comment by mpapis** [comment]
https://github.com/rvm/rvm-binary#invocation - I admit it could be improved, but should give you direction already.
