### ISSUE TITLE
Canary: is this project dead?

### ISSUE THREAD

**Issue by ms-ati** [rvm/rvm-binary#32]
Hi @mpapis and others, thank you so much for RVM over the years!

If this project is still considered alive, simply responding to this issue and closing it would be great!

**Comment by pkuczynski** [comment]
This project is definitely not dead :) We keep maintaining main rvm repo and help people when we can. Some people build binaries for various platforms, mainly Ubuntu

**Comment by pkuczynski** [comment]
Any new maintainers are welcome! :)
